### ISSUE TITLE
Temporary NuGet Id for Forms.Presenters

### ISSUE THREAD

**Issue by PeterBurke** [MvvmCross/MvvmCross-Forms#11]
I am currently restructuring the solution and will issue a Pull Request.

What I have in mind is that the Solution that compiles the Samples will not also compile the Forms.Presenter's, and will not reference them by project reference. Instead it will reference them via a NuGet package reference. This will help prove that the NuGet packages actually work as intended.

However the Pack.bat is missing the API key for the package identity: **Cirrious.MvvmCross.Forms.Presenter**. So it should because anyone could obtain it from GitHub.

What I propose is that I create a different Identity while preparing the PR for example it could be a random guid etc. Then once the PR has been reviewed one of us can update NuGet.

**Comment by Cheesebaron** [comment]
You don't need to upload the packages to NuGet to test that they work.

**Comment by PeterBurke** [comment]
Thanks

Sent from my Windows Phone
________________________________
