### ISSUE TITLE
Another PR out tomorrow / today

### ISSUE THREAD

**Issue by PeterBurke** [MvvmCross/MvvmCross-Forms#13]
ACTIVITY
========

- Minor restructure to remove WindowStore replaced by W81

- Added reference to a façade in Sample.iOS to address compile issue requested by Martijn van Dijk

- Added code provided by Huynh Khac Thao for Android to allow back and reopen

- Upgraded the sample to include an About page to demonstrate MvvMCross navigation

- W81 target was not showing a toolbar, added platform specific coding to fix

- Upgraded MvvMCross package references to 4.0.0.0-Alpha2, upgraded Xamarin reference to latest stable

- Re-factored NuGet package references reducing the number of dependencies on Core MvvMCross to just 2

- Examples no longer link to Form Presenters via project reference and use NuGet package reference

- Restructured the MvvMCross-Forms NuSpec dependencies on Core MvvMCross. Details follow.

MvvMCross had five packages now reduced to four after the removal of the non functional Portable support. (Actually still mentioned as a dependency in some and I will issue a PR to remove) The remaining four are:

- **MvvMCross** Removed. This package had nothing but dependencies on the following three packages

- **MvvMCross.HotTuna.CrossCore** Retained as a MvvM-Forms dependency

- **MvvMCross.HotTuna,MvvMCrossLibraries** Retained as a MvvMCross-Forms dependency

- **MvvMCross.HotTuna.StarterPack** Removed. This package has no assemblies but provides content. Specifically it sets up CSharp and other "To Do" type files. This would make sense for someone wanting to get started without using the FormPresenters and without using the examples as a launching point. The trouble though with these is that it is no easy task to go from the starter pack to a fully functioning solution and here we are aiming to provide core working examples that will allow developers to fast track. Also If at any stage a developer gets things in a state where a reinstall is necessary, the reinstall will bring in all of the content and mix it up with the example coding, now that is simply too hard.

So now we should have a simple fast-track MvvMCross-Forms example solution that Xamarin developers can use as a starting point.

FOLLOWING PULL REQUEST
========================

I will provide an alternative PCL in the examples that is based on XAML rather than C#. Switching between the two can be achieved via a powershell command that will change a #define in the target CSPROJ files.

I will start a more complex example, one that has a menu page with Apps. Each App will demonstrate how to use a specific MvvMCross plugin. First has to be the WebBrowser plugin as per the CheeseBaron Movies. Second will be based on SQLite plugin.

**Comment by martijn00** [comment]
Thanks for the explanation @PeterBurke .One thing i would like to point out is that the reference error is not only in iOS but in all the presenter projects.

Also alpha3 is the latest but that one has a bug in the nuspec so it can't be installed into PCL's.

I am looking forward to this PR!

**Comment by PeterBurke** [comment]
I will take an extra day and prove that the solution compiles on 2013.

Yes I had the error in Alpha3 $9 I will upgrade if it is ready in time.

Sent from my Windows Phone
________________________________

**Comment by martijn00** [comment]
I think it will compile in 2013 because i can open it in there. If possible i would like that you already open the PR so i can review it today. Then maybe @Cheesebaron and me could find out the thing with alpha3 and make a new release somewhere soon.
