### ISSUE TITLE
PR due shortly

### ISSUE THREAD

**Issue by PeterBurke** [MvvmCross/MvvmCross-Forms#15]
I have a minor restructure almost ready:

- Restructured Samples directories to cope with a large number of Samples

- Each Sample has its own SLN file, but there is a BAT file at the root of the folders that will MSBUILD them all.

- The dev_pack.bat for local NuSpec has some documentation and has been upgraded and tested to install locally not only the assemblies and symbols but also the source code and this will allow us to debug down into the Forms Presenters layer.

- First Sample now has a C# pages and a XAML pages variant.

The one aspect that I need to address is the issue of releases working on VS 2013 but not VS 2015 and Vice Versa. There are no compatibility issues in the C# files, but there seem to be minor differences in the SLN and CSPROJ files required to get a clean compile. I will be doing my testing of VS 2013 on a different computer and will deliver alternative versions of the files that differ.

As an aside [Visual Studio 2013 update 5](https://www.visualstudio.com/en-us/news/vs2013-update5-vs.aspx) has just been released and I will be upgrading before I start testing, I suggest that you do likewise.

Also I have been working on the [MvvmCross-Forms Wiki](https://github.com/PeterBurke/MvvmCross-Forms/wiki). I presume the Wiki will actually come across in the PR, but in any case take a look at it, all feedback Welcome.

I expect that the PR will be available sometime in the next 24 hours.

**Comment by martijn00** [comment]
Thanks! I've now installed VS2015 too, and i see where the reference error comes from. In VS2015 it as you to add a reference to ObjectModel, even in Android. But if you just ignore that, the project still builds fine.
