### ISSUE TITLE
Core, Droid and WindowsPhone are missing references to Xamarin.Forms.Core.Design and Xamarin.Forms.Xaml.Design

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross-Forms#39]
When building I get warning about missing references to Xamarin.Forms.Core.Design and Xamarin.Forms.Xaml.Design.

Presumably someone added them manually or someone forgot to push packages.config and packages are not restored correctly.

**Comment by martijn00** [comment]
Fixed now. They were added manually by someone.
