### ISSUE TITLE
UAP nuspec missing reference to MvvmCross.Forms.Presenter.Core.* dll

### ISSUE THREAD

**Issue by Chery** [MvvmCross/MvvmCross-Forms#42]
I tried installing the Nuget package for a UWP app, but the nuget specs don't refer to MvvmCross.Forms.Presenter.Core.* for the UAP part, and this in turn leads to a missing assembly.

Can you please correct this issue, and publish an updated Nuget package?

**Comment by lothrop** [comment]
`MvvmCross.Forms.Presenter.Core.*` seems to be missing here: https://github.com/MvvmCross/MvvmCross-Forms/blob/master/nuspec/MvvmCross.Forms.Presenter.nuspec#L77

**Comment by Chery** [comment]
@Cheesebaron Can you please push a nuget update with the new specs, as this is a blocking issue for me? I think you are the only one that handles the nuget packages at the moment.

Thanks a lot.

**Comment by Cheesebaron** [comment]
Done.
