### ISSUE TITLE
References updated, .csproj old targets issue

### ISSUE THREAD

**Issue by ilkeuygun** [MvvmCross/MvvmCross-Forms#48]
Samples/Example001CSharp solution needs update on the Xamarin.Forms NuGet packages. When you do so, the old entries in .csproj are not updated, so it still throws an error if it cannot find the old targets file.

<Error Condition="!Exists('..\..\..\packages\Xamarin.Forms.2.0.1.6505\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\packages\Xamarin.Forms.2.0.1.6505\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.targets'))" />

But I uploaded Xamarin.Forms to 2.3.0.38-pre2 and there is an entry for error for that package so the above line has to be deleted.
### Steps to reproduce
1. Open Samples/Example001CSharp  solution.
2. Update NuGet packages for the solution. 
3. Build and get the above error.
4. See .csproj files of the updated solution.
### Expected behavior

The old entries should be removed and there should be no errors.
### Actual behavior

Above error is thrown and execution ends.
### Configuration

**Version:** 4.1.4

**Platform:** iOS/Android/Windows UWP,

NOTE: This can be related to Xamarin.Forms, not MvvmCross-Forms but it would be nice if you can check the outdated libraries and re-upload the solutions because most of the solutions in this repo do not work out of the box. I am filing the same error to Xamarin as well.

**Comment by martijn00** [comment]
Should be fixed a while ago.
