### ISSUE TITLE
SplitView

### ISSUE THREAD

**Issue by mdonogma** [MvvmCross/MvvmCross-Forms#57]
Here are two examples of using SplitView with with MVVMCross:.
http://depblog.weblogs.us/2015/11/23/mvvmcross-uwp-splitview/
https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiKrtL7kNzPAhXEpJQKHQtWAWsQtwIIHTAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPpeysFIINcY&usg=AFQjCNGUIMTvQV7iSNfzx36SyQcxIe6Mkg

Question:
How do i do this with MVVMCross-Forms?

**Comment by martijn00** [comment]
Questions should be posted on StackOverflow.
